name: Send On-Call Person to Slack
on:
  schedule:
    # Run every Monday at 9 AM PST (5 PM UTC)
cron: '0 17 * * 1'
jobs:
  send-oncall-slack:
    runs-on: ubuntu-latest
    steps:
name: Checkout repository
      uses: actions/checkout@v3

name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

name: Run script to send on-call person to Slack
      env:
        PAGERDUTY_API_TOKEN: ${{ secrets.PAGERDUTY_API_TOKEN }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
      run: python oncall_notifier.py